[log]
level = ""
dir = "/var/log/nwatch"

[message_queue]
type = "redis"

	[message_queue.redis]
    etcd_endpoints = ["http://localhost:2379"]
    etcd_dir = "/nw/redis-servers"
	etcd_ttl_ms = 1000
    # this agent will register and consume from these nodes
    member = "127.0.0.1:6379"
	queue_key = "qk-etcd"
